version: '3.8'

services:
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_files:/var/www/html
    networks:
      - inception
    depends_on:
      wordpress:
        condition: service_healthy
    restart: always
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}

  wordpress:
    build: ./wordpress
    container_name: wordpress
    volumes:
      - wordpress_files:/var/www/html
    networks:
      - inception
    depends_on:
      mariadb:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_NAME=${DB_NAME}
      - WORDPRESS_DB_USER=${DB_USER}
      - WORDPRESS_DB_PASSWORD=${DB_PASS}

  mariadb:
    build: ./mariadb
    container_name: mariadb
    volumes:
      - wordpress_db:/var/lib/mysql
    networks:
      - inception
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_ROOT_PASS}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - WP_ADMIN_USER=${WP_ADMIN_USER}
      - WP_ADMIN_PASS=${WP_ADMIN_PASS}

volumes:
  wordpress_files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mde-agui/data/wordpress
  wordpress_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mde-agui/data/database

networks:
  inception:
    driver: bridge
