version: '3.8'

services:
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_files:/var/www/html
    networks:
      - inception
    depends_on:
      wordpress:
        condition: service_healthy
    restart: always
    env_file:
      - .env
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}

  wordpress:
    build: ./wordpress
    container_name: wordpress
    volumes:
      - wordpress_files:/var/www/html
    networks:
      - inception
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_started
    restart: always
    healthcheck:
      test: ["CMD", "pidof", "php-fpm7.4"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    env_file:
      - .env
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_NAME=${DB_NAME}
      - WORDPRESS_DB_USER=${DB_USER}
      - WORDPRESS_DB_PASSWORD=${DB_PASS}
      - REDIS_PASS=${REDIS_PASS}
      - WORDPRESS_CONFIG_EXTRA=define('WP_DEBUG', true); define('WP_DEBUG_LOG', '/var/www/html/wp-debug.log); define('WP_DEBUG_DISPLAY', false);

  mariadb:
    build: ./mariadb
    container_name: mariadb
    volumes:
      - wordpress_db:/var/lib/mysql
    networks:
      - inception
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_ROOT_PASS}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - WP_ADMIN_USER=${WP_ADMIN_USER}
      - WP_ADMIN_PASS=${WP_ADMIN_PASS}

  redis:
    build: ./redis
    container_name: redis
    networks:
      - inception
    restart: always
    env_file:
      - .env
    environment:
      - REDIS_PASS=${REDIS_PASS}

  ftp:
    build:
      context: ./ftp
      args:
        DOMAIN_NAME: ${DOMAIN_NAME}
    container_name: ftp
    ports:
      - "20:20"
      - "21:21"
      - "10000-10100:10000-10100"
    volumes:
      - wordpress_files:/var/www/html
    networks:
      - inception
    restart: always
    env_file:
      - .env
    environment:
      - FTP_USER=${FTP_USER}
      - FTP_PASS=${FTP_PASS}
      - DOMAIN_NAME=${DOMAIN_NAME}

  static:
    build: ./static
    container_name: static
    ports:
      - "8080:8080"
    networks:
      - inception
    restart: always
    env_file:
      - .env
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}

  adminer:
    build: ./adminer
    container_name: adminer
    ports:
      - "8081:8081"
    networks:
      - inception
    restart: always
    env_file:
      - .env
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    depends_on:
      mariadb:
        condition: service_healthy

volumes:
  wordpress_files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mde-agui/data/wordpress
  wordpress_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mde-agui/data/database

networks:
  inception:
    name: inception
    driver: bridge
